baseURL: "https://nauda.dev"
languageCode: "vi-vn"
defaultContentLanguage: "vi"
title: Nâu Đá Dev
description: "Một cuốn sổ để tự nhắc mình phải ghi chép mỗi khi uống nâu đá. Kết quả mình toàn gọi bạc xỉu!"
summary: "Một cuốn sổ để tự nhắc mình phải ghi chép mỗi khi uống nâu đá. Kết quả mình toàn gọi bạc xỉu!"
paginate: 10
theme: papermod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# pygmentsUseClasses: true
googleAnalytics: G-S3HXXF77WZ

minify:
  disableXML: true
  minifyOutput: true

languages:
  vi:
    languageName: "Tiếng Việt"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Thư phòng
          url: /archives/
          weight: 5
        - name: Tag
          url: /tags/
          weight: 10
        - name: Chủ đề
          url: /categories/
          weight: 15
        - name: Tìm
          url: /search/
          weight: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Nâu Đá Dev
  description: "Một cuốn sổ để tự nhắc mình phải ghi chép mỗi khi uống nâu đá. Kết quả mình toàn gọi bạc xỉu!"
  author: Duy Trung
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShareButtons: ["facebook", "linkedin", "twitter"]
  ShowReadingTime: true
  # disableSpecial1stPost: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  TocOpen: false

  comments: true
  images: ["logo_with_text.png"]

  homeInfoParams:
    Title: "☕ Tí tách, tí tách"
    Content: >

      Một cuốn sổ để tự nhắc mình phải ghi chép mỗi khi uống nâu đá.
      {{% md %}}
      > _Cho anh ly bạc xỉu size vừa nhé!_
      {{% md %}}
  # <div class="flex flex-wrap items-center my3">
  #   <div class="col-12 md-col-6 md-col-6 py1">
  #     <img src="/caphe-phin.png" width="96" class="mx-auto" />
  #   </div>
  #   <div class="col-12 md-col-6 md-col-6 right-align py1">
  # <!-- Align is important here, must place at same align with the top level html tag -->
  # {{% md %}}
  #   Lốc xoáy, bọt trắng và đá lạnh

  #   Cà phê, bột bã, sữa ngọt sánh thơm

  #   Đời, đắng, chua, ngọt, chát

  #   Để quên, nhớ, để tận hưởng, nhâm nhi
  # {{% /md %}}
  #   </div>
  # </div>

  socialIcons:
    - name: github
      url: "https://github.com/bonniss"
    - name: RSS
      url: "index.xml"
  assets:
    disableHLJS: true
  # editPost:
  #     URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  #     Text: "Suggest Changes" # edit text
  #     appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  cover:
    # linkFullImages: true
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  fuseOpts:
    isCaseSensitive: false
    includeMatches: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.3
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary"]

markup:
  goldmark:
    renderer:
      unsafe: true
  # highlight:
  #     noClasses: true
  #     codeFences: true
  #     guessSyntax: true
  #     # hl_Lines: ""
  #     # lineNoStart:
  #     lineNos: false
  #     # lineNumbersInTable: true
  #     tabWidth: 4
  #     style: dracula
  # highlight:
  #     noClasses: true
  #     codeFences: true
  #     guessSyntax: false
  #     # hl_Lines: ""
  #     # lineNoStart:
  #     lineNos: true
  #     # lineNumbersInTable: true
  #     tabWidth: 4
  #     style: monokai-sublime
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: dracula
    tabWidth: 4

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

imaging:
  anchor: Smart
  bgColor: "#ff0000"
  hint: photo
  quality: 80
  resampleFilter: MitchellNetravali
  exif:
    disableDate: false
    disableLatLong: false
    excludeFields: ""
    includeFields: ""
