baseURL = "/"
languageCode = "vi-vn"
title = "Nâu Đá Dev"
theme = "papermod"

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "My Digital Garden on the Internet"
  images = ['/digital-garden-logo.png']

# [Params.newsletter]
#   title = ""
#   description = "A curated weekly digest once a week to your mailbox"
#   path = "https://www.getrevue.co/profile/username/add_subscriber"

[menu]
[[menu.main]]
  name = 'Trang chủ'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Bài viết'
  url = '/blog'
  weight = 2
[[menu.main]]
  name = 'Bài viếtt'
  url = '/archive'
  weight = 2
[[menu.main]]
  name = 'Chủ đề'
  url = '/categories'
  weight = 3
[[menu.main]]
  name = 'Tag'
  url = '/tags'
  weight = 4
# [[menu.main]]
#   name = 'Polywork'
#   url = 'https://polywork.com'
#   weight = 5

[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com'
  weight = 1
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com'
  weight = 2
# [[menu.social]]
#   name = 'LinkedIn'
#   url = 'https://linkedin.com'
#   weight = 3
# [[menu.social]]
#   name = 'Instagram'
#   url = 'https://instagram.com'
#   weight = 4
# [[menu.social]]
#   name = 'Dribbble'
#   url = 'https://dribbble.com'
#   weight = 5
[[menu.social]]
  name = 'Codepen'
  url = 'https://codepen.io'
  weight = 6
# [[menu.social]]
#   name = 'Twitch'
#   url = 'https://twitch.com'
#   weight = 7
# [[menu.social]]
#   name = 'Email'
#   url = 'mailto:user@example.org'
#   weight = 8
# [[menu.social]]
#   name = 'RSS'
#   url = '/articles/index.xml'
#   weight = 9


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
