baseURL: "https://nauda.dev"
languageCode: "vi-vn"
defaultContentLanguage: "vi"
title: Nâu Đá Dev
paginate: 5
theme: papermod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-S3HXXF77WZ

minify:
    disableXML: true
    minifyOutput: true

languages:
    vi:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Thư phòng
                  url: /archives/
                  weight: 5
                - name: Tag
                  url: /tags/
                  weight: 10
                - name: Chủ đề
                  url: /categories/
                  weight: 15
                - name: Tìm
                  url: /search/
                  weight: 20

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Nhâm nháp một ly cà phê sữa, và tán gẫu, với Duy Trung, về đủ thứ, nhưng lập trình là chủ đạo nhé"
    author: Duy Trung

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShareButtons: ["facebook", "linkedin", "twitter"]
    ShowReadingTime: true
    # disableSpecial1stPost: false
    displayFullLangName: true
    ShowPostNavLinks: true
    # ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    TocOpen: true

    comments: true
    images: ["papermod-cover.png"]

    homeInfoParams:
        Title: "Tí tách, tí tách"
        Content: >
            Ồ, đã ghé qua thì ngồi chơi, tán gẫu, ngắm cà phê nhỏ giọt với Trung nào.

            - <img src="/favicon.png" width="75" class="mx-auto" style="margin: 2rem auto" />

              Lốc xoáy, bọt trắng và đá lạnh

              Cà phê, bột bã, sữa ngọt sánh thơm

              Đời, đắng, chua, ngọt, chát

              Để quên, nhớ, để tận hưởng, nhâm nhi

    socialIcons:
        - name: github
          url: "https://github.com/bonniss"
        - name: RsS
          url: "index.xml"

    # editPost:
    #     URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    analytics:
        google:
            SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: true # hide on single page

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 5000
        threshold: 0.75
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary"]

assets:
    disableHLJS: true
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        # hl_Lines: ""
        # lineNoStart: 1
        # lineNos: true
        # lineNumbersInTable: true
        tabWidth: 4
        style: dracula

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true