baseURL: "/"
languageCode: "vi-vn"
defaultContentLanguage: "vi"
title: "Đen Đá Dev"
theme: "anubis"
paginate: 10
enableRobotsTXT: true
enableEmoji: true

menu:
  main:
  - identifier: archive
  #   name: Archive
  #   title: Archive
  #   url: /categories/developer/
  #   weight: 0
  # - identifier: psychology
  #   name: Psychology
  #   title: Psychology
  #   url: /categories/psychology/
  #   weight: 0

# taxonomies:
# # Disable the default taxonomies
#   tag: ""
#   category: ""

# permalinks:
#   tag: "tag/:slug"
#   category: "danh-muc/:slug"

params:
  author: "Duy Trung"
  email: "duytrung.tcu@gmail.com"
  avatar: "/images/me.png"
  description: ""
  readMore: false
  mainSections: ["lap-trinh", "tuy-hung", "tam-ly-hoc"]
  paginationSinglePost: true
  style: dark
  dateFormat: "02/01/2006"
  showCredit: false
  themeSwitcherPosition: "header"
  hasAside: true
  asideSticky: true

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
