baseURL: "/"
languageCode: "vi-vn"
defaultContentLanguage: "vi"
title: "Nâu Đá Dev"
theme: "anubis"
paginate: 10
enableRobotsTXT: true
enableEmoji: true

menu:
  main:
  - identifier: archive
  #   name: Archive
  #   title: Archive
  #   url: /categories/developer/
  #   weight: 0
  # - identifier: psychology
  #   name: Psychology
  #   title: Psychology
  #   url: /categories/psychology/
  #   weight: 0

# taxonomies:
# # Disable the default taxonomies
#   tag: ""
#   category: ""

# permalinks:
#   tag: "tag/:slug"
#   category: "danh-muc/:slug"

minify:
  minifyOutput: true

params:
  author: "Duy Trung"
  email: "duytrung.tcu@gmail.com"
  avatar: "/images/me.png"
  siteLogo:
    url: "/logo.png"
    size: 56
  description: "Chỉ là cuốn sổ ghi chép của Duy Trung về lập trình: Javascript, PHP, Python; và nhiều thứ hay ho nữa"
  readMore: false
  mainSections: ["blog", "about"]
  paginationSinglePost: true
  style: dark
  dateFormat: "02/01/2006"
  showCredit: false
  themeSwitcherPosition: "header"
  hasAside: true
  asideSticky: true

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
