backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads"
collections:
  - name: "developer" # Used in routes, e.g., /admin/collections/blog
    label: "Developer" # Used in the UI
    folder: "content/developer" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{year}}{{month}}{{day}}-" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      # - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Created Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}